In [1]:
import numpy as np
import time
from timeit import default_timer as timer

# Налаштування для акуратного виведення
np.set_printoptions(suppress=True, precision=3)

Завдання 1

In [2]:
# -------------------------------------------------------------------------------
# Вправа 3. Створення масиву з "нульовими" рядками та стовпцями (n x m, r-й рядок, c-й стовпець)
# -------------------------------------------------------------------------------
n, m, r, c = 6, 7, 2, 3
print(f"Вправа 3. Вхідні дані: n={n}, m={m}, r={r}, c={c}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
A_np = np.ones((n, m), dtype=int)
A_np[::r] = 0        # Нулі у кожному r-му рядку
A_np[:, ::c] = 0     # Нулі у кожному c-му стовпці
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 3: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
A_loop = [[1 for j in range(m)] for i in range(n)]
for i in range(n):
    if i % r == 0:
        A_loop[i] = [0] * m
    else:
        for j in range(m):
            if j % c == 0:
                A_loop[i][j] = 0
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 3: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")

Вправа 3. Вхідні дані: n=6, m=7, r=2, c=3

--- Вправа 3: NumPy ---
Результат:
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
Час виконання: 0.000198 с

--- Вправа 3: Цикли ---
Результат:
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
Час виконання: 0.000170 с


In [3]:
# -------------------------------------------------------------------------------
# Вправа 4. Матриця з індексами у першому рядку (n x m, перший рядок від 0 до m-1)
# -------------------------------------------------------------------------------
n, m = 3, 4
print(f"\n\nВправа 4. Вхідні дані: n={n}, m={m}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
A_np = np.zeros((n, m), dtype=int)
A_np[0, :] = np.arange(m) # Заповнення першого рядка
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 4: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
A_loop = []
for i in range(n):
    if i == 0:
        row = [j for j in range(m)] # Спискове включення для першого рядка
    else:
        row = [0] * m
    A_loop.append(row)
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 4: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 4. Вхідні дані: n=3, m=4

--- Вправа 4: NumPy ---
Результат:
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Час виконання: 0.000229 с

--- Вправа 4: Цикли ---
Результат:
[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
Час виконання: 0.000153 с


In [4]:
# -------------------------------------------------------------------------------
# Вправа 5. Матриця з одиницями в парних рядках (n x n, парні індекси = 1, непарні = 0)
# -------------------------------------------------------------------------------
n = 5
print(f"\n\nВправа 5. Вхідні дані: n={n}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
A_np = np.zeros((n, n), dtype=int)
A_np[::2, :] = 1 # Слайсінг для парних індексів
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 5: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
A_loop = []
for i in range(n):
    if i % 2 == 0:
        row = [1] * n
    else:
        row = [0] * n
    A_loop.append(row)
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 5: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 5. Вхідні дані: n=5

--- Вправа 5: NumPy ---
Результат:
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
Час виконання: 0.000194 с

--- Вправа 5: Цикли ---
Результат:
[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
Час виконання: 0.000118 с


In [5]:
# -------------------------------------------------------------------------------
# Вправа 6. Заміна ненульових елементів на -1
# -------------------------------------------------------------------------------
data_list = [3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3]
data = np.array(data_list)
print(f"\n\nВправа 6. Початковий масив: {data}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
A_np = data.copy()
A_np[A_np != 0] = -1 # Булева індексація
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 6: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
A_loop = data.tolist()
for i in range(len(A_loop)):
    if A_loop[i] != 0:
        A_loop[i] = -1
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 6: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 6. Початковий масив: [3 4 0 9 7 0 6 0 4 0 3]

--- Вправа 6: NumPy ---
Результат:
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Час виконання: 0.001730 с

--- Вправа 6: Цикли ---
Результат:
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]
Час виконання: 0.000354 с


In [6]:
# -------------------------------------------------------------------------------
# Вправа 7. Заміна нульових елементів на -1
# -------------------------------------------------------------------------------
data_list = [3, 4, 0, 6, 5, 0, 3, 0, 4]
data = np.array(data_list)
print(f"\n\nВправа 7. Початковий масив: {data}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
A_np = data.copy()
A_np[A_np == 0] = -1 # Булева індексація
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 7: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
A_loop = data.tolist()
for i in range(len(A_loop)):
    if A_loop[i] == 0:
        A_loop[i] = -1
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 7: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 7. Початковий масив: [3 4 0 6 5 0 3 0 4]

--- Вправа 7: NumPy ---
Результат:
[ 3  4 -1  6  5 -1  3 -1  4]
Час виконання: 0.000125 с

--- Вправа 7: Цикли ---
Результат:
[ 3  4 -1  6  5 -1  3 -1  4]
Час виконання: 0.000096 с


In [7]:
# -------------------------------------------------------------------------------
# Вправа 8. Підрахунок нульових та ненульових елементів
# -------------------------------------------------------------------------------
data_list = [3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0]
data = np.array(data_list)
print(f"\n\nВправа 8. Початковий масив: {data}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
zeros_np = np.sum(data == 0)
non_zeros_np = np.count_nonzero(data)
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 8: NumPy ---")
print(f"Нулів: {zeros_np}")
print(f"Не нулів: {non_zeros_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
zeros_loop = 0
non_zeros_loop = 0
for element in data_list:
    if element == 0:
        zeros_loop += 1
    else:
        non_zeros_loop += 1
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 8: Цикли ---")
print(f"Нулів: {zeros_loop}")
print(f"Не нулів: {non_zeros_loop}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 8. Початковий масив: [3 4 0 9 8 2 4 0 8 4 0]

--- Вправа 8: NumPy ---
Нулів: 3
Не нулів: 8
Час виконання: 0.002914 с

--- Вправа 8: Цикли ---
Нулів: 3
Не нулів: 8
Час виконання: 0.000240 с


In [8]:
# -------------------------------------------------------------------------------
# Вправа 9. Створення масиву значень від n до 0
# -------------------------------------------------------------------------------
n = 10
print(f"\n\nВправа 9. Вхідні дані: n={n}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
A_np = np.arange(n, -1, -1) # Створення послідовності
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 9: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Спискове включення)
start_time_loop = timer()
A_loop = [i for i in range(n, -1, -1)]
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 9: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 9. Вхідні дані: n=10

--- Вправа 9: NumPy ---
Результат:
[10  9  8  7  6  5  4  3  2  1  0]
Час виконання: 0.000125 с

--- Вправа 9: Цикли ---
Результат:
[10  9  8  7  6  5  4  3  2  1  0]
Час виконання: 0.000143 с


In [9]:
# -------------------------------------------------------------------------------
# Вправа 13. Шаховий порядок 8 х 8 (за допомогою *)
# -------------------------------------------------------------------------------
n = 8
print(f"\n\nВправа 13. Розмір матриці: {n}x{n}")

## Спосіб a) NumPy (Векторизація) - використовуємо np.tile
start_time_np = timer()
pattern = np.array([0, 1])
row1 = np.tile(pattern, n // 2)
row2 = np.tile(pattern[::-1], n // 2)
A_np = np.vstack([row1, row2] * (n // 2))
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 13: NumPy ---")
print(f"Результат:\n{A_np}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Спискове включення з *)
start_time_loop = timer()
pattern1 = [0, 1] * (n // 2)
pattern2 = [1, 0] * (n // 2)
A_loop = []
for i in range(n):
    if i % 2 == 0:
        A_loop.append(pattern1)
    else:
        A_loop.append(pattern2)
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 13: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 13. Розмір матриці: 8x8

--- Вправа 13: NumPy ---
Результат:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Час виконання: 0.002563 с

--- Вправа 13: Цикли ---
Результат:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Час виконання: 0.000207 с


In [10]:
# -------------------------------------------------------------------------------
# Вправа 19. Вектор із рівномірно розміщених елементів (0, 1)
# -------------------------------------------------------------------------------
n = 10
print(f"\n\nВправа 19. Вхідні дані: n={n}")

## Спосіб a) NumPy (Векторизація)
start_time_np = timer()
# linspace(початок, кінець, кількість точок).
# Створюємо n+2 точки, щоб відкинути крайні (0 і 1)
A_np = np.linspace(0, 1, n + 2)[1:-1]
A_np_rounded = np.round(A_np, 3)
end_time_np = timer()
time_np = end_time_np - start_time_np
print("\n--- Вправа 19: NumPy ---")
print(f"Результат (округлено до 3 знаків):\n{A_np_rounded}")
print(f"Час виконання: {time_np:.6f} с")

## Спосіб b) Ітеративні конструкції (Цикли)
start_time_loop = timer()
step = 1.0 / (n + 1)
A_loop = []
for i in range(1, n + 1):
    value = i * step
    A_loop.append(round(value, 3))
end_time_loop = timer()
time_loop = end_time_loop - start_time_loop
print("\n--- Вправа 19: Цикли ---")
print(f"Результат:\n{np.array(A_loop)}")
print(f"Час виконання: {time_loop:.6f} с")



Вправа 19. Вхідні дані: n=10

--- Вправа 19: NumPy ---
Результат (округлено до 3 знаків):
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]
Час виконання: 0.000406 с

--- Вправа 19: Цикли ---
Результат:
[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]
Час виконання: 0.000198 с


2. Завдання: Розв'язання системи лінійних алгебраїчних рівнянь

In [11]:
# Матриця коефіцієнтів A та вектор вільних членів b
A = np.array([
    [2, 1, -5, 1],
    [1, -3, 0, -6],
    [0, 2, -1, 2],
    [1, 4, -7, 6]
], dtype=float)

b = np.array([8, 9, -5, 0], dtype=float)

print("Матриця A:\n", A)
print("Вектор b:", b)

# 1. Розв'язання за формулами Крамера
Delta = np.linalg.det(A)
print(f"\n1. Головний визначник Delta: {Delta:.3f}")

if np.isclose(Delta, 0):
    print("Визначник близький до нуля, формули Крамера можуть бути неточними або незастосовними.")
else:
    # Обчислення допоміжних визначників
    A1, A2, A3, A4 = A.copy(), A.copy(), A.copy(), A.copy()

    A1[:, 0], A2[:, 1], A3[:, 2], A4[:, 3] = b, b, b, b

    Delta1 = np.linalg.det(A1)
    Delta2 = np.linalg.det(A2)
    Delta3 = np.linalg.det(A3)
    Delta4 = np.linalg.det(A4)

    x_kramer = np.array([Delta1 / Delta, Delta2 / Delta, Delta3 / Delta, Delta4 / Delta])
    print(f"Розв'язок за Крамером (x_kramer):\n{x_kramer}")

    # 2. Перевірки
    print("\n--- Перевірки ---")

    # a) Розв'язок за допомогою np.linalg.solve()
    x_solve = np.linalg.solve(A, b)
    print(f"Розв'язок через np.linalg.solve() (x_solve):\n{x_solve}")

    # b) Розв'язок за допомогою оберненої матриці
    A_inv = np.linalg.inv(A)
    x_inv = A_inv @ b # @ - оператор матричного множення
    print(f"Розв'язок через обернену матрицю (x_inv):\n{x_inv}")

    # c) Перевірка матричним множенням для Крамера: A * X = B
    b_check = A @ x_kramer
    print(f"Перевірка Крамера: A * x_kramer = {b_check}")

    # 3. Порівняння всіх рішень
    print("\n--- Порівняння за допомогою numpy.allclose() ---")
    print(f"Крамер vs. np.linalg.solve(): {np.allclose(x_kramer, x_solve)}")
    print(f"Крамер vs. обернена матриця: {np.allclose(x_kramer, x_inv)}")
    print(f"np.linalg.solve() vs. обернена матриця: {np.allclose(x_solve, x_inv)}")

    print("\nВисновок: Усі методи дають однаковий результат (у межах точності обчислень).")

Матриця A:
 [[ 2.  1. -5.  1.]
 [ 1. -3.  0. -6.]
 [ 0.  2. -1.  2.]
 [ 1.  4. -7.  6.]]
Вектор b: [ 8.  9. -5.  0.]

1. Головний визначник Delta: 27.000
Розв'язок за Крамером (x_kramer):
[ 3. -4. -1.  1.]

--- Перевірки ---
Розв'язок через np.linalg.solve() (x_solve):
[ 3. -4. -1.  1.]
Розв'язок через обернену матрицю (x_inv):
[ 3. -4. -1.  1.]
Перевірка Крамера: A * x_kramer = [ 8.  9. -5.  0.]

--- Порівняння за допомогою numpy.allclose() ---
Крамер vs. np.linalg.solve(): True
Крамер vs. обернена матриця: True
np.linalg.solve() vs. обернена матриця: True

Висновок: Усі методи дають однаковий результат (у межах точності обчислень).


3. Завдання: Обчислення значення матричного виразу

In [12]:
# --- Визначення матриць ---
A = np.array([
    [5, 3, -1],
    [2, -2, 0],
    [3, -1, 2]
], dtype=float)

B = np.array([
    [1, 4, 16],
    [-3, -2, 0],
    [5, 7, 2]
], dtype=float)

print("Матриця A:\n", A)
print("Матриця B:\n", B)

# --- Спосіб a) NumPy (Векторизація) [cite: 21] ---
start_time_np = timer()
# $2(A-0,5B) + A \cdot B$
X_np = 2 * (A - 0.5 * B) + A @ B # @ - оператор матричного множення
end_time_np = timer()
time_np = end_time_np - start_time_np

print("\n--- NumPy (Векторизація) ---")
print(f"Результат X:\n{X_np}")
print(f"Час виконання: {time_np:.6f} с")


# --- Спосіб b) Ітеративні конструкції (Цикли) [cite: 22, 23] ---

# Допоміжні функції для циклів (можна використовувати функції з Завдання 2, якщо вони були створені)
def mat_add_sub_loop(M1, M2, sign=1): # sign=1 для додавання, -1 для віднімання
    R = np.zeros_like(M1)
    for i in range(M1.shape[0]):
        for j in range(M1.shape[1]):
            R[i, j] = M1[i, j] + sign * M2[i, j]
    return R

def mat_mul_loop(M1, M2):
    rows_1, cols_1 = M1.shape
    rows_2, cols_2 = M2.shape
    R = np.zeros((rows_1, cols_2))
    for i in range(rows_1):
        for j in range(cols_2):
            sum_val = 0
            for k in range(cols_1):
                sum_val += M1[i, k] * M2[k, j]
            R[i, j] = sum_val
    return R

start_time_loop = timer()

# 1. 0.5 * B
B_half_loop = 0.5 * B
# 2. A - 0.5 * B
A_minus_B_half_loop = mat_add_sub_loop(A, B_half_loop, sign=-1)
# 3. 2 * (A - 0.5 * B)
C_loop = 2 * A_minus_B_half_loop
# 4. A * B
D_loop = mat_mul_loop(A, B)
# 5. X = C + D
X_loop = mat_add_sub_loop(C_loop, D_loop, sign=1)

end_time_loop = timer()
time_loop = end_time_loop - start_time_loop

print("\n--- Ітеративні конструкції (Цикли) ---")
print(f"Результат X:\n{X_loop}")
print(f"Час виконання: {time_loop:.6f} с")

# --- Порівняння результатів та часу [cite: 24] ---
print("\n--- Порівняння ---")
print(f"Чи збігаються результати (np.allclose): {np.allclose(X_np, X_loop)}")
print(f"NumPy час: {time_np:.6f} с")
print(f"Ітеративний час: {time_loop:.6f} с")
print("Висновок: NumPy (векторизація) швидший за ітеративний підхід завдяки оптимізованим операціям.")

Матриця A:
 [[ 5.  3. -1.]
 [ 2. -2.  0.]
 [ 3. -1.  2.]]
Матриця B:
 [[ 1.  4. 16.]
 [-3. -2.  0.]
 [ 5.  7.  2.]]

--- NumPy (Векторизація) ---
Результат X:
[[ 0.  9. 60.]
 [15. 10. 32.]
 [17. 19. 54.]]
Час виконання: 0.000269 с

--- Ітеративні конструкції (Цикли) ---
Результат X:
[[ 0.  9. 60.]
 [15. 10. 32.]
 [17. 19. 54.]]
Час виконання: 0.000377 с

--- Порівняння ---
Чи збігаються результати (np.allclose): True
NumPy час: 0.000269 с
Ітеративний час: 0.000377 с
Висновок: NumPy (векторизація) швидший за ітеративний підхід завдяки оптимізованим операціям.
